### ISSUE TITLE
Set up everything, but still get "User does not have sufficient permissions for this profile."

### ISSUE THREAD

**Issue by aldidas** [spatie/laravel-analytics#40]
Hi,

I've set up all parameter needed by this package :

ANALYTICS_SITE_ID=ga:xxxxxxxxx
ANALYTICS_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxx
ANALYTICS_SERVICE_EMAIL=account-1@xxxxxxxxxxx-xxxx.iam.gserviceaccount.com

The ANALYTICS_SERVICE_EMAIL has been added to my analytics user through the GA admin interface, and I've uploaded the .p12 file into my server (storage folder).

But I still get the (403) User does not have sufficient permissions for this profile. 

It seems the API Credentials has been changed, since the format that I get was different from that mentioned in the readme section.

Anyone get the same error like this?

Thanks.

**Comment by lion2486** [comment]
I have the same problem and with google/apiclient package too. I think that the problem may be that the google console have changed the credential form (I see than an older server key had an client-id with email-form). I am searching for the solution too. Thanks.

**Comment by freekmurze** [comment]
I'll update the readme the next time I'll have to go through the procudure my self again. I'd welcome a PR that updates the readme.

**Comment by gjportegies** [comment]
@aldidas did you change the 'certificatePath' to the uploaded .p12 file?

        /*
         * You need to download a p12-certifciate from the Google API console
         * Be sure to store this file in a secure location.
         */
        'certificatePath' => storage_path('laravel-analytics/your-p12-file-here.p12'),

**Comment by BrandonSurowiec** [comment]
I found that the siteId is actually supposed to be the analytic's "View Id". Using that number solved it for me.

**Comment by kimoi** [comment]
Hi - wondering why this was closed? The differences between the dashboard and the readme are confusing. There's nothing I can see that looks like a "client id" (The closest thing is the key id - but that's just an identify for the keyfile, hence the name)

If I can figure it out I'll submit a PR

**Comment by haiderghaleb** [comment]
Did anyone figure out the solution regarding the client id, I tried all kind of solutions and still getting User does not have sufficient permissions for this profile.

**Comment by kimoi** [comment]
I generated a service email and key from within the API dashboard. I then added that email address to the allowed users list for the property I want to access.

**Comment by haiderghaleb** [comment]
@kimoi I fixed it by specifying my analytic profile id table, but if you try to configure it on the general analytic id it won't work.

**Comment by N02SRT** [comment]
I am still having issues getting the client ID, Is there an easy way to do this? Sorry I am new to Google Analytics.

**Comment by gamingumar** [comment]
mine is working fine without adding client ID. just leave it blank it works fine without it.

**Comment by verybigelephants** [comment]
> I found that the siteId is actually supposed to be the analytic's "View Id". Using that number solved it for me.

**THIS**

find the "client id" and write the "siteId" into configuration as "ga:thenumber"

i have no idea what is clientId

**Comment by DigitalCoder** [comment]
Hi !
I'm going to ask a silly question but where exactly can I find my ANALYTICS_SITE_ID starting with ga: ?

Thx

**Comment by DigitalCoder** [comment]
ANALYTICS_SITE_ID is equal to  ga:ANALYTICS_VIEW_ID  ???

**Comment by verybigelephants** [comment]
honestly, this has got to be the worst third party tool i've ever worked with. it's nice of the devs to make it usable by public but the configuration mess is almost as bad as doing my taxes

**Comment by freekmurze** [comment]
@verybigelephants  we like to keep the conversation constructive here. Here are a few things you can do to make this package better:

- be specific in what you think is wrong with the package
- suggest ways to improve it
- submit a PR to improve something (code, README, ...)
